/*
 * HmAiTranslatorToEn v1.0.0.1
 *
 * Copyright (c) 2024 Akitsugu Komiyama
 * under the MIT License
 */

jsmode @"WebView2\HmGoogleGemini";
js {

var _globalSelectedTextOfAiTranslator = "";
function onRequestQuestionText() {
    return "次の「文章もしくは単語」を英語に翻訳してください。翻訳結果のみを応答してください。\n\n---\n\n" + _globalSelectedTextOfAiTranslator;
}

function onCompleteAnswerText(answer_text) {
    answer_text = answer_text.replace(/\n+$/, '\n');
    insert(answer_text);
}

function doMyCustomMain() {
    _globalSelectedTextOfAiTranslator = hidemaru.getSelectedText();
    if (_globalSelectedTextOfAiTranslator == "") {
        let dll = loaddll(hidemaruExeDir + "\\HmOutputPane.dll");
        dll.dllfunc.Output(hidemaru.getCurrentWindowHandle(), "選択テキストがありません\r\n");
        return;
    }

    const targetAiMacroPath = macrodir()+"\\HmGoogleGemini\\HmGoogleGemini.mac";

    const argobj = {
        onRequestQuestionText: 1,
        onCompleteAnswerText: 1
    };

    hidemaru.setTimeout(
        () => { hidemaru.postExecMacroFile(`"${targetAiMacroPath}"`, argobj); },
    0 );
}

doMyCustomMain();


} // js

